sudo: required
services:
  - docker
language: node_js
env:
  - CI: true
node_js: 6
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_35fbdff035d9_key -iv $encrypted_35fbdff035d9_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
install:
  - docker build . -t gift-me
script:
  - docker run --entrypoint npm gift-me test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: giftme-161622
  version: dev
  docker_build: local
  no_promote: true
  on:
    all_branches: true
