FROM node:6
MAINTAINER Aaron Buxbaum "me@aaronbuxbaum.com"

RUN apt-get update -y -qq
RUN apt-get install -y -qq python python-dev python-pip expect-dev

COPY . /app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN npm install --silent
RUN npm rebuild node-sass

CMD unbuffer supervisord -c supervisord.conf
EXPOSE 3000
VOLUME /app/src