version: '3'

services:
  node:
    build: .
    container_name: node
    environment:
      CI: '${CI}'
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    working_dir: /app

  python:
    build: ./api
    container_name: python
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app/api
    working_dir: /app/api
