version: '3'

services:
  node:
    build: .
    environment:
      CI: '${CI}'
    volumes:
      - ./src:/app/src
    working_dir: /app

  python:
    build: ./api
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app/api
    working_dir: /app/api
