version: '3'

services:
  nginx:
    build: ./nginx
    links:
      - node
      - python
    ports:
      - 80:80
        
  node:
    build: .
    command: npm run start
    environment:
      CI: '${CI}'
    expose:
      - 8000
    volumes:
      - ./src:/app/src
    working_dir: /app

  python:
    build: ./api
    command: python hello.py
    expose:
      - 3000
    volumes:
      - ./api:/app/api
    working_dir: /app/api
